version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    env_file:
      # BE SURE TO CHANGE THIS LINE BEFORE GOING TO PRODUCTION
      - ./postgres.env
    ports:
      - '5433:5432'
    volumes:
      - postgres-lib:/var/lib/postgresql/data
  influxdb:
    container_name: influxdb
    image: influxdb:2.4.0-alpine
    volumes:
      - influxdb-lib:/var/lib/influxdb2
    env_file:
      # BE SURE TO CHANGE THIS LINE BEFORE GOING TO PRODUCTION
      - ./influx2.env
    ports:
      - 8086:8086
    restart: always
    privileged: true

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:9.1.6
    volumes:
      - ./grafana/etc:/etc/grafana:ro
      - grafana-lib:/var/lib/grafana
      - grafana-log:/var/log/grafana
    links:
      - influxdb:influxdb
    env_file:
      # BE SURE TO CHANGE THIS LINE BEFORE GOING TO PRODUCTION
      - ./grafana.env
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    restart: always
    privileged: true

volumes:
  postgres-lib:
    external: false

  influxdb-lib:
    external: false

  grafana-lib:
    external: false

  grafana-log:
    external: false
