{
 "title": "SmartHome",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Temperatura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatura wody",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water_temperature_sensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"thermometer_id\"] == \"3c01f095d8f4\" or r[\"thermometer_id\"] == \"01183362faff\" or r[\"thermometer_id\"] == \"011833561aff\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatura wody 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"default-dawnsampled-5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water_temperature_sensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"thermometer_id\"] == \"3c01f095d8f4\" or r[\"thermometer_id\"] == \"01183362faff\" or r[\"thermometer_id\"] == \"011833561aff\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "SATEL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Aktywność poszczególnych wejść",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"input\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device\"] == \"2\")\n  |> aggregateWindow(every: 5m, fn: count)\n  |> yield(name: \"increase\")"
    }
   ]
  },
  {
   "title": "Sumaryczna aktywność wejść",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"input\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"device\"] == \"2\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 5m, fn: count)\n  |> yield(name: \"count\")"
    }
   ]
  },
  { "title": "Dziennik zdarzeń", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Centrala inteligentnego domu (Core)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elixir_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"msg\")\n  |> filter(fn: (r) => r[\"app\"] == \"core\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> yield(name: \"sort\")"
    }
   ]
  }
 ]
}